dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper
  scan:
    base-packages: com.king.service
spring:
  application:
    name: dubbo-provider

server:
  port: 8849